const defaultProducts=[
{id:'sf-001',name:'Runner 01 / Graphite',category:'sneakers',price:12900,color:'Graphite',tone:'dark',tag:'NEW',sizes:'39, 40, 41, 42, 43',stock:8,description:'Лёгкая городская модель с мягкой посадкой и контрастной подошвой.'},
{id:'sf-002',name:'Court Low / Cream',category:'sneakers',price:11400,color:'Cream / Lime',tone:'lime',tag:'BESTSELLER',sizes:'36, 37, 38, 39, 40',stock:14,description:'Минималистичный силуэт на каждый день. Акцентная деталь — фирменная лаймовая подошва.'},
{id:'sf-003',name:'Heavyweight Hoodie',category:'apparel',price:8900,color:'Washed black',tone:'dark',sizes:'S, M, L, XL',stock:11,description:'Плотный хлопковый худи со свободной посадкой и вышитым логотипом.'},
{id:'sf-004',name:'Utility Cap / Orange',category:'accessories',price:3900,color:'Burnt orange',tone:'orange',sizes:'One size',stock:20,description:'Шесть панелей, регулируемый ремешок и цвет, который собирает весь образ.'},
{id:'sf-005',name:'Wide Denim 02',category:'apparel',price:9700,color:'Raw indigo',tone:'dark',sizes:'28, 30, 32, 34',stock:7,description:'Широкие джинсы из плотного денима с высокой посадкой.'},
{id:'sf-006',name:'Trail 02 / Bone',category:'sneakers',price:13900,color:'Bone / Black',tone:'orange',tag:'DROP 04',sizes:'40, 41, 42, 43, 44',stock:5,description:'Треккинговый характер, городской комфорт и цепкая подошва.'},
{id:'sf-007',name:'Logo Tee / Acid',category:'apparel',price:4500,color:'Acid green',tone:'lime',sizes:'S, M, L, XL',stock:18,description:'Мягкая футболка свободного кроя с графикой STREETFORM.'},
{id:'sf-008',name:'Crossbody Pack',category:'accessories',price:5900,color:'Black nylon',tone:'dark',sizes:'One size',stock:9,description:'Компактная сумка для телефона, ключей и всего необходимого.'}
];
let products=JSON.parse(localStorage.getItem('streetform-products')||'null')||defaultProducts;
let cart=JSON.parse(localStorage.getItem('streetform-cart')||'[]');
let activeCategory='all';let query='';let sortMode='newest';let pendingImage='';
const money=n=>new Intl.NumberFormat('ru-RU').format(Number(n)||0)+' ₽';
const save=()=>{localStorage.setItem('streetform-products',JSON.stringify(products));localStorage.setItem('streetform-cart',JSON.stringify(cart));};
const grid=document.querySelector('#productGrid');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function productArt(p,detail=false){return p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy">`:`<div class="product-art">SF</div>`}
function renderProducts(){let filtered=products.filter(p=>(activeCategory==='all'||p.category===activeCategory||(activeCategory==='sale'&&p.price<6000))&&(!query||`${p.name} ${p.color} ${p.category} ${p.description||''} ${p.sizes||''}`.toLowerCase().includes(query.toLowerCase())));filtered=[...filtered].sort((a,b)=>sortMode==='price-low'?a.price-b.price:sortMode==='price-high'?b.price-a.price:sortMode==='name'?a.name.localeCompare(b.name):0);document.querySelector('#resultCount').textContent=`${filtered.length} ${filtered.length===1?'товар':'товаров'}`;document.querySelector('#clearSearch').hidden=!query;grid.innerHTML=filtered.map(p=>`<article class="product-card ${p.image?'has-image':''}"><div class="product-image" data-tone="${p.tone||'dark'}">${p.tag?`<span class="product-tag">${esc(p.tag)}</span>`:''}${productArt(p)}</div><div class="product-info"><div><p class="product-name">${esc(p.name)}</p><small class="product-meta">${esc(p.color)}${p.stock!==undefined?' · в наличии '+p.stock:''}</small></div><span class="product-price">${money(p.price)}</span></div><p class="product-description">${esc(p.description||'Подробности о товаре скоро появятся.')}</p><div class="product-details"><span>Размеры: ${esc(p.sizes||'уточняйте')}</span><span>${p.stock>0?'В наличии':'Нет в наличии'}</span></div><button class="product-more" data-details="${p.id}">Подробнее ↗</button><button class="product-add" data-add="${p.id}" ${p.stock===0?'disabled':''}>${p.stock===0?'Нет в наличии':'Добавить в bag +'}</button></article>`).join('');document.querySelector('#emptyState').hidden=filtered.length>0;}
function renderCart(){const count=cart.reduce((s,i)=>s+i.qty,0);document.querySelector('#cartCount').textContent=count;document.querySelector('#cartItemsLabel').textContent=`${count} ${count===1?'item':'items'}`;document.querySelector('#cartTotal').textContent=money(cart.reduce((s,i)=>s+i.price*i.qty,0));document.querySelector('#cartItems').innerHTML=cart.length?cart.map(i=>`<div class="cart-row"><div class="cart-thumb">${i.image?`<img src="${esc(i.image)}" alt="">`:'SF'}</div><div><p>${esc(i.name)}</p><small>${money(i.price)}</small></div><div class="qty"><button data-qty="${i.id}" data-delta="-1">−</button><span>${i.qty}</span><button data-qty="${i.id}" data-delta="1">+</button></div></div>`).join(''):'<p class="empty-state">Твоя bag пока пустая.</p>';}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p||p.stock===0)return;const item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({...p,qty:1});save();renderCart();openCart();}
function openCart(){document.querySelector('#cartDrawer').classList.add('open');document.querySelector('#overlay').classList.add('open')}
function closeCart(){document.querySelector('#cartDrawer').classList.remove('open');document.querySelector('#overlay').classList.remove('open')}
function renderAdmin(){document.querySelector('#adminList').innerHTML=products.map(p=>`<div class="admin-row"><div class="admin-row-thumb">${p.image?`<img src="${esc(p.image)}" alt="">`:'SF'}</div><div>${esc(p.name)}<br><small>${esc(p.category)} · ${esc(p.color)} · ${p.stock??'—'} шт.</small></div><input type="number" min="0" value="${p.price}" data-price="${p.id}"/><button class="edit-product" data-edit="${p.id}">Изменить</button><button class="delete-product" data-delete="${p.id}">Удалить</button></div>`).join('');}
function resetAdminForm(){document.querySelector('#adminForm').reset();document.querySelector('#adminEditingId').value='';document.querySelector('#adminSave').textContent='Добавить товар';document.querySelector('#adminCancelEdit').hidden=true;pendingImage='';document.querySelector('#imageName').textContent='PNG, JPG или WEBP';document.querySelector('#imagePreview').innerHTML='<span>Предпросмотр фото</span>';}
function fillAdminForm(p){document.querySelector('#adminEditingId').value=p.id;document.querySelector('#adminName').value=p.name;document.querySelector('#adminPrice').value=p.price;document.querySelector('#adminCategory').value=p.category;document.querySelector('#adminColor').value=p.color||'';document.querySelector('#adminSizes').value=p.sizes||'';document.querySelector('#adminStock').value=p.stock??'';document.querySelector('#adminDescription').value=p.description||'';document.querySelector('#adminImage').value=p.image&&p.image.startsWith('http')?p.image:'';pendingImage=p.image||'';document.querySelector('#adminSave').textContent='Сохранить изменения';document.querySelector('#adminCancelEdit').hidden=false;document.querySelector('#imagePreview').innerHTML=p.image?`<img src="${esc(p.image)}" alt="Предпросмотр">`:'<span>Предпросмотр фото</span>';}
function showDetails(id){const p=products.find(x=>x.id===id);if(!p)return;document.querySelector('#productDetail').innerHTML=`<div class="detail-image" data-tone="${p.tone||'dark'}">${productArt(p,true)}</div><div class="detail-copy"><p class="eyebrow">${esc(p.category)} / STREETFORM</p><h3>${esc(p.name)}</h3><div class="detail-price">${money(p.price)}</div><p class="detail-description">${esc(p.description||'Подробности о товаре скоро появятся.')}</p><div class="detail-specs">Цвет: ${esc(p.color||'—')}<br>Размеры: ${esc(p.sizes||'уточняйте')}<br>Остаток: ${p.stock??'уточняется'} шт.</div><button class="button button-dark detail-add" data-add="${p.id}" ${p.stock===0?'disabled':''}>${p.stock===0?'Нет в наличии':'Добавить в bag ↗'}</button></div>`;document.querySelector('#productDialog').showModal();}
document.querySelector('#categories').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;document.querySelectorAll('.filter-button').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeCategory=b.dataset.category;renderProducts()});
grid.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add)addToCart(add.dataset.add);const details=e.target.closest('[data-details]');if(details)showDetails(details.dataset.details)});
document.querySelector('#productDetail').addEventListener('click',e=>{const b=e.target.closest('[data-add]');if(b){addToCart(b.dataset.add);document.querySelector('#productDialog').close()}});
document.querySelector('#cartItems').addEventListener('click',e=>{const b=e.target.closest('[data-qty]');if(!b)return;const i=cart.find(x=>x.id===b.dataset.qty);if(!i)return;i.qty+=Number(b.dataset.delta);if(i.qty<1)cart=cart.filter(x=>x.id!==i.id);save();renderCart()});
document.querySelector('#cartOpen').onclick=openCart;document.querySelector('#cartClose').onclick=closeCart;document.querySelector('#overlay').onclick=closeCart;document.querySelector('#detailClose').onclick=()=>document.querySelector('#productDialog').close();
document.querySelector('#searchToggle').onclick=()=>{document.querySelector('#searchBar').classList.toggle('open');document.querySelector('#searchInput').focus()};document.querySelector('#searchInput').oninput=e=>{query=e.target.value.trim();renderProducts()};document.querySelector('#clearSearch').onclick=()=>{query='';document.querySelector('#searchInput').value='';renderProducts()};document.querySelector('#sortSelect').onchange=e=>{sortMode=e.target.value;renderProducts()};
document.querySelector('#menuToggle').onclick=()=>document.querySelector('.main-nav').classList.toggle('open');
document.querySelector('#checkoutButton').onclick=()=>alert('Для приёма заказов подключи Telegram-бота или платёжную систему. Сейчас это демо-оформление.');
document.querySelector('#newsletterForm').onsubmit=e=>{e.preventDefault();document.querySelector('#newsletterMessage').textContent='Готово — проверяй почту для подтверждения.';e.target.reset()};
const dialog=document.querySelector('#adminDialog');document.querySelector('#adminOpen').onclick=()=>{resetAdminForm();renderAdmin();dialog.showModal()};document.querySelector('#adminClose').onclick=()=>dialog.close();document.querySelector('#adminCancelEdit').onclick=resetAdminForm;
document.querySelector('#adminImageFile').onchange=e=>{const file=e.target.files?.[0];if(!file)return;document.querySelector('#imageName').textContent=file.name;const reader=new FileReader();reader.onload=()=>{pendingImage=reader.result;document.querySelector('#imagePreview').innerHTML=`<img src="${pendingImage}" alt="Предпросмотр">`};reader.readAsDataURL(file)};
document.querySelector('#adminImage').oninput=e=>{if(!e.target.value)return;pendingImage=e.target.value;document.querySelector('#imagePreview').innerHTML=`<img src="${esc(pendingImage)}" alt="Предпросмотр">`};
document.querySelector('#adminForm').onsubmit=e=>{e.preventDefault();const name=document.querySelector('#adminName').value.trim();const price=Number(document.querySelector('#adminPrice').value);if(!name||Number.isNaN(price))return;const id=document.querySelector('#adminEditingId').value;const payload={name,price,category:document.querySelector('#adminCategory').value,color:document.querySelector('#adminColor').value||'New color',sizes:document.querySelector('#adminSizes').value||'уточняйте',stock:Number(document.querySelector('#adminStock').value||0),description:document.querySelector('#adminDescription').value||'',image:pendingImage||'',tone:'lime'};if(id){const p=products.find(x=>x.id===id);Object.assign(p,payload)}else products.unshift({id:'sf-'+Date.now(),...payload});save();renderProducts();renderAdmin();resetAdminForm()};
document.querySelector('#adminList').addEventListener('change',e=>{if(!e.target.dataset.price)return;const p=products.find(x=>x.id===e.target.dataset.price);if(p){p.price=Number(e.target.value);save();renderProducts();renderAdmin()}});document.querySelector('#adminList').addEventListener('click',e=>{const edit=e.target.closest('[data-edit]');if(edit){fillAdminForm(products.find(x=>x.id===edit.dataset.edit));return}const del=e.target.closest('[data-delete]');if(!del)return;products=products.filter(x=>x.id!==del.dataset.delete);cart=cart.filter(x=>x.id!==del.dataset.delete);save();renderProducts();renderCart();renderAdmin()});document.querySelector('#adminReset').onclick=()=>{products=JSON.parse(JSON.stringify(defaultProducts));save();renderProducts();renderAdmin();resetAdminForm()};
renderProducts();renderCart();
